env:
  browser: true
  es2021: true
extends:
  - standard
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:jest/recommended
  - eslint-config-prettier # 最後に追加
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
rules: { 'no-useless-constructor': 'off' }
ignorePatterns:
  - '/dist'
